# Generated by Django 3.0.3 on 2020-06-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=18)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
