# Generated by Django 3.0.3 on 2020-06-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20200617_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
