# Generated by Django 3.0.3 on 2020-06-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20200617_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='desc',
        ),
    ]
