# Generated by Django 3.0.3 on 2020-06-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_auto_20200619_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='name',
            new_name='person_name',
        ),
    ]
