# Generated by Django 3.0.3 on 2020-06-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_auto_20200619_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='person_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
