# Generated by Django 3.0.3 on 2020-06-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_auto_20200620_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_name', models.CharField(blank=True, max_length=120, null=True)),
                ('review', models.TextField(max_length=250, null=True)),
                ('image', models.ImageField(default='', upload_to='mysite/images')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='person_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(default='', max_length=250),
        ),
    ]
