# Generated by Django 3.0.3 on 2020-06-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_auto_20200622_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='review',
            new_name='ser_desc',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(default='', upload_to='mysite/images'),
        ),
        migrations.AlterField(
            model_name='review',
            name='person_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=250),
        ),
    ]
