# Generated by Django 3.0.3 on 2020-06-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_auto_20200623_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
