# Generated by Django 3.0.3 on 2020-06-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_auto_20200623_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_type',
            field=models.CharField(choices=[('web', 'Web'), ('app', 'App')], default='web', max_length=20),
        ),
    ]
