# Generated by Django 3.0.3 on 2020-06-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0027_auto_20200623_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='job_or_post',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
