# Generated by Django 3.0.3 on 2020-06-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0028_auto_20200623_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='job_or_post',
            new_name='jobpost',
        ),
    ]
