# Generated by Django 3.0.3 on 2020-06-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0030_auto_20200628_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.TextField(max_length=400, null=True)),
                ('p2', models.TextField(max_length=400, null=True)),
                ('p3', models.TextField(max_length=400, null=True)),
                ('ab_image', models.FileField(default='', upload_to='about/images')),
            ],
        ),
    ]
