# Generated by Django 3.0.3 on 2020-06-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0032_auto_20200629_0951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
