# Generated by Django 3.0.3 on 2020-07-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0038_auto_20200701_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='map_url',
        ),
    ]
